---
- name: Jira - Download Jira.
  get_url:
    url: "{{ jira_download_url }}"
    dest: "{{ jira_app_dir }}/jira.tar.gz"
    tmp_dest: "{{ tmp_dest }}"
- name: Jira - Uncompress downloaded file.
  unarchive:
    src: "{{ jira_app_dir }}/jira.tar.gz"
    dest: "{{ jira_app_dir }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    copy: no
- name: Jira - Remove downloaded file.
  file:
    path: "{{ jira_app_dir }}/jira.tar.gz"
    state: absent
