---
- name: restart jira service
  systemd:
    name: "jira"
    state: restarted

- name: stop jira service
  systemd:
    name: "jira"
    state: stop

- name: start jira service
  systemd:
    name: "jira"
    state: started
    daemon_reload: "{{ jira_systemd_daemon_reload }}"
    enabled: "{{ jira_systemd_enable }}"
